language: node_js
node_js: node
services:
  - mongodb
deploy:
  provider: heroku
  api_key:
    secure: dLtRPqQfQfeiV/VJ5uhofv78GJuSnO6a9I/gVA9DBAIoBxWC8A49FzBduplzQ6l7OpTFRxHpwaJpngXDQI8aQ0ePwheckumkVrMWcL/rI5X4iC6iFJLd11gGSsq71v+J6MfSWTXOpkTxPTwsnaAqLK2sVnX4Dk2SYrquNNRafcXKFFwSM25r1/fk7xed+Bewev4HoyaLze5EgPWqgpB1WOIKRTXn47zzusp1khDiyflxMzLFhZPmzENm/yi7NIfvSSkET9Dssr/rj4LPglzhYYn7co3TWD6v9/lTGFbsMOD1Zoj28hxzjq3AGjuF7g/Mblq1tEvbrdIy72GHd2k4lYW8fBxHzn3CryrQSkDKKnJwIj4RyxrwECESPaINb3VhIQlFPWrApLoA6duK1hc7amR6HqLntaGR4TdW42ABkQNMF4fsCo9hxp8Tl3h9CLEdGEr/4S5UJK7TVrUzaMLD5wQIe2jOB+VN7/HIRS+JN4rdWonCHTw0ly3PCt8KzvS19noQtxdUPnM90maFqMT7kgfOYB1u67FHJ4roR97KFdrcFoWVszSiF/3nD3Fw9aXtLTPk65RDO/qjSwUaT2R3rh09OX9V2ndXsVAmiTYYbKw5V4OFOAE1p0pZDboYE1B8lKDgZEc+GQYrlb2LDs84NRMryok/vGDxjIJ+ohDLE84=
  app: my-acronym-dictionary
  on:
    repo: iastanley/my-acronym-dictionary-app
